package:
  name: pyopcode
  version: 0.3.3

source:
  path: ..

build:
  number: 3
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py>=35]

requirements:
  build:
  - python
  - setuptools
  - cmake
  - numpy 1.11.3
  - boost 1.61.0
  - pyyaml 3.12

  run:
  - python
  - numpy 1.11.3
  - boost 1.61.0

test:
  commands:
    - py.test --pyargs pyopcode
  imports:
    - pyopcode
  requires:
    - pytest >=3.0

about:
  home: https://github.com/ClinicalGraphics/pyopcode
  license: LGPL-3.0
  summary: OPCODE collision detection wrapped library with numpy bindings (mesh-mesh and mesh-ray)