about:
  home: hhttps://github.com/ClinicalGraphics/pyopcode
  license: LGPL
  summary: OPCODE collision detection wrapped library with numpy bindings
build:
  features:
  - vc9                [win and py27]
  - vc10               [win and py34]
  - vc14               [win and py35]
  number: 0
  preserve_egg_dir: true
package:
  name: pyopcode
  version: 0.1.dev7
requirements:
  build:
  - gcc 4.8.2 [linux]
  - cmake 3.5*
  - boost
  - python
  - numpy 1.10*
  - pyyaml 3.11*
  - setuptools
  run:
  - python
  - boost
  - libgcc [linux]
  - numpy 1.10*
  - future
source:
  path: ..
test:
  imports:
  - pyopcode
